/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotelmanagementsystem;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patch
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        curDate();
        curTime();
        addnewRoom();



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jSelectRoomNo = new javax.swing.JComboBox<>();
        jCheckOutButton = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabelName1 = new javax.swing.JLabel();
        jCheckInButton1 = new javax.swing.JButton();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelError = new javax.swing.JLabel();
        jComboBoxSelectRow = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableGuest = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaTotal = new javax.swing.JTextArea();
        jLabelName = new javax.swing.JLabel();
        jLabelName2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaCash = new javax.swing.JTextArea();
        jLabelName3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaGivenChange = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPrintButton = new javax.swing.JButton();
        jLabelName4 = new javax.swing.JLabel();
        jResetButton = new javax.swing.JButton();
        jChangeButton = new javax.swing.JButton();
        jPayButton = new javax.swing.JButton();
        jTextFieldCashInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1340, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmail.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelEmail.setText("Email :");
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 40));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hotel Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 40));

        jLabelPhone.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelPhone.setText("Phone :");
        jPanel1.add(jLabelPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 40));

        jSelectRoomNo.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jSelectRoomNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel1.add(jSelectRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 380, 60));

        jCheckOutButton.setText("CheckOut");
        jCheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckOutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 100, 50));

        time.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        time.setText("Time");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 140, 80));

        date.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        date.setText("Date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, 80));

        jLabelName1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelName1.setText("Name :");
        jPanel1.add(jLabelName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 40));

        jCheckInButton1.setText("Check In");
        jCheckInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckInButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckInButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 90, 50));
        jPanel1.add(jTextFieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 270, 40));

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 72, 270, 40));

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 270, 40));

        jLabelError.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 270, -1));

        jPanel1.add(jComboBoxSelectRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 410, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 480));

        jTableGuest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RoomNo", "CustomerName", "Email", "Phone", "RoomType", "CheckInTime", "CheckOutTime", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableGuest.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane4.setViewportView(jTableGuest);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 870, 480));

        jPanel2.setBorder(jPanel1.getBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Phone", "RoomType", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 330));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 550, 350));

        jPanel3.setBorder(jPanel1.getBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaTotal.setColumns(20);
        jTextAreaTotal.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jTextAreaTotal.setRows(5);
        jScrollPane3.setViewportView(jTextAreaTotal);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 260, 90));

        jLabelName.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelName.setText("Total");
        jPanel3.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 40));

        jLabelName2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelName2.setText("Cash");
        jPanel3.add(jLabelName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 40));

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaCash.setColumns(20);
        jTextAreaCash.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jTextAreaCash.setRows(5);
        jScrollPane6.setViewportView(jTextAreaCash);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 260, 90));

        jLabelName3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelName3.setText("Change");
        jPanel3.add(jLabelName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 40));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaGivenChange.setColumns(20);
        jTextAreaGivenChange.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jTextAreaGivenChange.setRows(5);
        jScrollPane7.setViewportView(jTextAreaGivenChange);

        jPanel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 260, 90));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 380, 350));

        jPanel4.setBorder(jPanel1.getBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPrintButton.setText("Print");
        jPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrintButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jPrintButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 300, 50));

        jLabelName4.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabelName4.setText("Cash");
        jPanel4.add(jLabelName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        jResetButton.setText("Reset");
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 140, 50));

        jChangeButton.setText("Change");
        jChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 140, 50));

        jPayButton.setText("Pay");
        jPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPayButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jPayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 50));
        jPanel4.add(jTextFieldCashInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 32, 240, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 350, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class customerArr{
    
        public customer newCustomer(String cClass, String Name , String Email , int Phone){
            return new customer(Name, Email , Phone);
        }
    }

    private void jPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrintButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrintButtonActionPerformed

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jResetButtonActionPerformed

    private void jChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChangeButtonActionPerformed

    private void jPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPayButtonActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jCheckInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckInButton1ActionPerformed
        // TODO add your handling code here:
        

        Integer selectedRoom = Integer.valueOf(jSelectRoomNo.getSelectedItem().toString());
        
        for ( int i = 0 ; i < jTableGuest.getRowCount() ; i ++ ) {
            if ( jSelectRoomNo.getSelectedIndex() != 0 ) {
                if (!(jTextFieldName.getText().equals(null)) || !(jTextFieldEmail.getText().equals(null)) || !(jTextFieldPhone.getText().equals(null))) {
                    String name = jTextFieldName.getText();
                    String email = jTextFieldEmail.getText();
                    String phone = (jTextFieldPhone.getText());
                    String CheckInTime = getCurrentTime(); 
                    if (jTableGuest.getModel().getValueAt(i, 0).equals(selectedRoom)) {
                        jLabelError.setText("");
                        jTableGuest.setValueAt(name, i, 1);
                        jTableGuest.setValueAt(email, i, 2);
                        jTableGuest.setValueAt(phone, i, 3);
                        jTableGuest.setValueAt(CheckInTime, i, 5);
                        jTableGuest.setValueAt(null, i, 6);
                    
                        jTextFieldName.setText("");
                        jTextFieldEmail.setText("");
                        jTextFieldPhone.setText("");
                        jSelectRoomNo.setSelectedIndex(0);
                        jComboBoxSelectRow.addItem(phone);
                }
                    
                } else {
                    jLabelError.setText("*Please fill the form*");
                }
                
                
                
                
                 
            }
        }
        
        
//
//
////        Object[] newRow = { row , name , email , phone , selectedRoom, CheckInTime , null };
////        dtm.addRow(newRow);
//
//        jTableGuest.setModel(dtm);        
//        Object selectedRoomObj = jSelectRoomNo.getSelectedItem();
//        String selectedRoom = selectedRoomObj.toString();
//        String classname = selectedRoom;
//        try {
//            Class<?> Cls = Class.forName(classname);
//
//            Object Room = Cls.newInstance();
//            if(Room instanceof StandardRoom || Room instanceof SuperiorRoom || Room instanceof DeluxeRoom || Room instanceof SuiteRoom){
//                Room STRoom = (Room) Room;
//                Double Price = STRoom.Price;
//
//                DefaultTableModel Reciept =(DefaultTableModel) jTable1.getModel();
//
//                int row = addnewRow();
//                String name = jTextFieldName.getText();
//                String email = jTextFieldEmail.getText();
//                String phone = (jTextFieldPhone.getText());
//                String CheckInTime = getCurrentTime();
//
//                 if ((jTextFieldName.getText().equals("")) ||
//                        (jTextFieldEmail.getText().equals("")) ||
//                        (jTextFieldPhone.getText().equals("")) ||
//                        ((jSelectRoom.getSelectedIndex()) == 0))
//                {
//                    jLabelError.setText("Please fill the form");
//                } else {
//                    jLabelError.setText("");
//
//                    Object[] newRowPaid = { name , email , phone , selectedRoom, Price };
//                    Reciept.addRow(newRowPaid);
//
//                    jTextFieldName.setText("");
//                    jTextFieldEmail.setText("");
//                    jTextFieldPhone.setText("");
//                    jSelectRoom.setSelectedIndex(0);
//                    jComboBoxSelectRow.addItem(phone);
//
//
//                }
//
//                 jTable1.setModel(Reciept);
//            }
//
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
//        }catch (InstantiationException e) {
//            System.err.println("Error instantiating class: " + e.getMessage());
//        } catch (IllegalAccessException e) {
//            System.err.println("Illegal access to class: " + e.getMessage());
//        }

//        DefaultTableModel dtm =(DefaultTableModel) jTableGuest.getModel();
//
//        int row = addnewRow();
//        String name = jTextFieldName.getText();
//        String email = jTextFieldEmail.getText();
//        String phone = (jTextFieldPhone.getText());
//        String CheckInTime = getCurrentTime();
//
//        if ((jTextFieldName.getText().equals("")) ||
//                (jTextFieldEmail.getText().equals("")) ||
//                (jTextFieldPhone.getText().equals("")) ||
//                ((jSelectRoomNo.getSelectedIndex()) == 0))
//        {
//
//            jLabelError.setText("Please fill the form");
//        } else {
//            jLabelError.setText("");
//            Object[] newRow = { row , name , email , phone , selectedRoom, CheckInTime , null };
//            Object[] newRowPaid = { row , name , email , phone , selectedRoom, CheckInTime , null };
//            dtm.addRow(newRow);
//
//            jTextFieldName.setText("");
//            jTextFieldEmail.setText("");
//            jTextFieldPhone.setText("");
//            jSelectRoomNo.setSelectedIndex(0);
//            jComboBoxSelectRow.addItem(phone);
//
//
//        }
//
//
////        Object[] newRow = { row , name , email , phone , selectedRoom, CheckInTime , null };
////        dtm.addRow(newRow);
//
//        jTableGuest.setModel(dtm);


    }//GEN-LAST:event_jCheckInButton1ActionPerformed

    private void jCheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckOutButtonActionPerformed
        // TODO add your handling code here:
        String SelectedCheckOut = (String) jComboBoxSelectRow.getSelectedItem();
        
        for ( int j = 0 ; j < jTableGuest.getRowCount() ; j++) {
            if (SelectedCheckOut != null) {
                if (jTableGuest.getValueAt(j, 3) == SelectedCheckOut ) {
                    if (jTableGuest.getValueAt(j, 6) == null ) {
                    jTableGuest.setValueAt(getCurrentTime(), j, 6);
                    }
                }
            }
        }
    }//GEN-LAST:event_jCheckOutButtonActionPerformed

    public void curDate(){

        Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("yyyy/dd/MM");
                String curdate  = s.format(d);
                date.setText(curdate);
    }

    public void curTime(){
        new Timer(0, new ActionListener() {


            @Override
            public void actionPerformed(ActionEvent e) {
               Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                String curtime  = s.format(d);
                time.setText(curtime);
            }

        }).start();
    }

    public void addnewRoom() {


        StandardRoom st101 = new StandardRoom(101,"Standard");
        StandardRoom st102 = new StandardRoom(102,"Standard");
        StandardRoom st103 = new StandardRoom(103,"Standard");
        StandardRoom st104 = new StandardRoom(104,"Standard");

        SuperiorRoom sp201 = new SuperiorRoom(201,"Superior");
        SuperiorRoom sp202 = new SuperiorRoom(202,"Superior");
        SuperiorRoom sp203 = new SuperiorRoom(203,"Superior");
        SuperiorRoom sp204 = new SuperiorRoom(204,"Superior");

        Room dl301 = new DeluxeRoom(301,"Deluxe");
        Room dl302 = new DeluxeRoom(302,"Deluxe");
        Room dl303 = new DeluxeRoom(303,"Deluxe");
        Room dl304 = new DeluxeRoom(304,"Deluxe");

        SuiteRoom su401 = new SuiteRoom(401,"Suite");


        addnewRowtoGuest(st101);
        addnewRowtoGuest(st102);
        addnewRowtoGuest(st103);
        addnewRowtoGuest(st104);
        addnewRowtoGuest(sp201);
        addnewRowtoGuest(sp202);
        addnewRowtoGuest(sp203);
        addnewRowtoGuest(sp204);
        addnewRowtoGuest(dl301);
        addnewRowtoGuest(dl302);
        addnewRowtoGuest(dl303);
        addnewRowtoGuest(dl304);
        addnewRowtoGuest(su401);

        ArrayList<Integer> RoomList = new ArrayList<Integer>();
        RoomList.add(st101.roomNo);
        RoomList.add(st102.roomNo);
        RoomList.add(st103.roomNo);
        RoomList.add(st104.roomNo);
        RoomList.add(sp201.roomNo);
        RoomList.add(sp202.roomNo);
        RoomList.add(sp203.roomNo);
        RoomList.add(sp204.roomNo);
        RoomList.add(dl301.roomNo);
        RoomList.add(dl302.roomNo);
        RoomList.add(dl303.roomNo);
        RoomList.add(dl304.roomNo);
        RoomList.add(su401.roomNo);
        
        ArrayList<String> RoomListstr = new ArrayList<String>();
        
        for (Integer item : RoomList) {
            String stringValue = Integer.toString(item);
            RoomListstr.add(stringValue);
        }

        for (int i = 0 ; i < RoomListstr.size(); i++ ) {
           jSelectRoomNo.addItem(RoomListstr.get(i));
        }

    }


    public String getCurrentTime() {
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String formatDateTime = now.format(format);
        return formatDateTime;
    }

    public void addnewRowtoGuest(Room room) {
            DefaultTableModel dtm =(DefaultTableModel) jTableGuest.getModel();
            Object[] newRow = {room.roomNo,null,null,null,room.Type,null,null,room.Price};
            dtm.addRow(newRow);
            jTableGuest.setModel(dtm);
        ;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    class Room {
        Integer roomNo;
        Double Price;
        String Type;
        Room(int RoomNo,String type) {
           this.roomNo = RoomNo;
           this.Type = type;
        }

        public int getRoomNo() {
            return roomNo;
        }

        public Double getPrice() {
            return Price;
        }
    }

    class StandardRoom extends Room {

        public StandardRoom(int RoomNo ,String type) {
            super(RoomNo, "Standard");
            Price = 2000.00;
        }

    }

    class SuperiorRoom extends Room {
        public SuperiorRoom(int RoomNo ,String type) {
            super(RoomNo, "Superior");
            Price = 2500.00;
        }
    }

    class DeluxeRoom extends Room {
        public DeluxeRoom(int RoomNo,String type) {
            super(RoomNo , "Deluxe");

            Price = 3000.00;
        }
    }

    class SuiteRoom extends Room {
        public SuiteRoom(int RoomNo,String type) {
            super(RoomNo, "Suite");
            Price = 3500.00;
        }
    }

    class customer{
        int Cash;
        String Name;
        String Email;
        int Phone;
        int Change;

        public customer(String inName ,String inEmail,  int inPhone ) {
            this.Name = inName;
            this.Email = inEmail;
            this.Phone = inPhone;
        }  
    }
    
    class ReserveGuest extends customer{

        Date ReserveDate ;
        public ReserveGuest() {
            super(null, null,0);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JButton jChangeButton;
    private javax.swing.JButton jCheckInButton1;
    private javax.swing.JButton jCheckOutButton;
    private javax.swing.JComboBox<String> jComboBoxSelectRow;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JLabel jLabelName2;
    private javax.swing.JLabel jLabelName3;
    private javax.swing.JLabel jLabelName4;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jPayButton;
    private javax.swing.JButton jPrintButton;
    private javax.swing.JButton jResetButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JComboBox<String> jSelectRoomNo;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableGuest;
    private javax.swing.JTextArea jTextAreaCash;
    private javax.swing.JTextArea jTextAreaGivenChange;
    private javax.swing.JTextArea jTextAreaTotal;
    private javax.swing.JTextField jTextFieldCashInput;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
